force-app/main/default/objects/TestChildObj__c/TestChildObj__c.object-meta.xml
<CustomObject>
    <label>TestChildObj</label>
    <nameField>
        <displayFormat>TCH-{00000}</displayFormat>
        <label>TestChildObj Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TestChildObjs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TestChildObj__c/fields/TestObj__c.field-meta.xml
<CustomField>
    <fullName>TestObj__c</fullName>
    <label>TestObj</label>
    <referenceTo>TestObj__c</referenceTo>
    <relationshipLabel>TestChildObjs</relationshipLabel>
    <relationshipName>TestChildObjs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TestObj__c/TestObj__c.object-meta.xml
<CustomObject>
    <label>TestObj</label>
    <nameField>
        <label>TestObj Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TestObjs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DualListController.cls
public class DualListController {
	@AuraEnabled(cacheable = true)
    public static List<TestObj__c> ParentList(){
        return [SELECT Id, Name FROM TestObj__c];
    }
    
    @AuraEnabled(cacheable = true)
    public static List<TestChildObj__c> ChildList(string parentId){
        //string idString = ParentId+'%';
        list<TestChildObj__c> ChildObjs =  [SELECT Id, Name FROM TestChildObj__c WHERE TestObj__c =:ParentId];
        if(ChildObjs.size()>0){
            return ChildObjs;
        }
        else{
            return null;
        }
    }
}