force-app/main/default/objects/TestChildObj__c/TestChildObj__c.object-meta.xml
<CustomObject>
    <label>TestChildObj</label>
    <nameField>
        <displayFormat>TCH-{00000}</displayFormat>
        <label>TestChildObj Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TestChildObjs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TestChildObj__c/fields/TestObj__c.field-meta.xml
<CustomField>
    <fullName>TestObj__c</fullName>
    <label>TestObj</label>
    <referenceTo>TestObj__c</referenceTo>
    <relationshipLabel>TestChildObjs</relationshipLabel>
    <relationshipName>TestChildObjs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TestObj__c/TestObj__c.object-meta.xml
<CustomObject>
    <label>TestObj</label>
    <nameField>
        <label>TestObj Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TestObjs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestObjController.cls
public class TestObjController {
	@AuraEnabled(cacheable=true)
    public static list<testObj__c> allRecords(){
        return [SELECT Id, Name FROM TestObj__c LIMIT 200];
    }
    @AuraEnabled(cacheable=true)
    public static list<TestChildObj__c> allChildRecords(){
        return [SELECT Id, Name FROM TestChildObj__c LIMIT 200];
    }
    @AuraEnabled(cacheable=true)
    public static void listBuilderMethod(list<id> idList){
        system.debug('ID list');
        for(string str : idList){
            system.debug(str);
        }
    }
}